### ISSUE TITLE
How solve this?

### ISSUE THREAD

**Issue by erolando** [souzainf3/RNActivityView#3]
[self.tableView showActivityViewWithLabel:@"Conexión se interrumpio" image:[UIImage imageNamed:@"image.png"]];

![screen shot 2014-10-07 at 13 11 21](https://cloud.githubusercontent.com/assets/1770136/4547486/90239fbc-4e4d-11e4-9344-f29434f27949.png)

**Comment by souzainf3** [comment]
Hi @erolando 
You called component (RNActivityView) through its UITableView instance . Thus the " RNActivityView " will be a subview , the "separators/rows " of UITableView are created at runtime , These will be front .

Call this component through the UIWindow or a view that is not a subclass of UITableView.
