### ISSUE TITLE
Crash rn_dealloc

### ISSUE THREAD

**Issue by efipeek** [souzainf3/RNActivityView#4]
Hello, I have a mistake when i use your librairie. In fact, my application crash when i use RnActivityView, i quit the view and i go to another view which use RNActivityView. The crash is located at : 

- (void)rn_dealloc {
    [self destroyActivityView];
    
    //this calls original dealloc method
    [self rn_dealloc];
}

When I comment "[self.rn_dealloc]" no crash occurs. How I can resolve this error ? 
EXC_BAD_ACCESS(code=1, address=0x77534955)

Thanks

**Comment by souzainf3** [comment]
Fixed. thanks @efipeek @oschobel
