### ISSUE TITLE
AppStore safe?

### ISSUE THREAD

**Issue by euroboy** [souzainf3/RNActivityView#6]
I would like to know if using these classes is safe for AppStore submission? Thanks.

**Comment by souzainf3** [comment]
@euroboy 
Yes. It's is safe. I use in various projects. Including is big projects as:
[Zee Personal Finance](https://itunes.apple.com/us/app/zee-personal-finance/id422694086?mt=8)
[Telecine Play](https://itunes.apple.com/us/app/telecine-play-filmes-online/id542237176?mt=8)
[Globosat Play](https://itunes.apple.com/us/app/globosat-play-sportv-gnt-multishow/id453880374?mt=8)
[Esporte Interativo](https://itunes.apple.com/us/app/esporte-interativo-ei-plus/id509496846?mt=8)

Among others.

Feel free to test, suggest improvements. Pull request are welcome.
